- .prettierignore
- .prettierrc
- eslint.config.js
- package.json
- src/main.jsx
- vite.config.js
- ESLint와 Prettier 설정 파일 추가 및 구성
- 코드 스타일 자동화를 위한 패키지 설치
- `.prettierrc` 및 `.prettierignore` 파일 생성
- `eslint.config.js` 파일에 포맷팅 및 코드 규칙 추가
-  React 컴포넌트 작성 스타일 규칙 추가(export default function 형식 사용)
> 🔧 chore: ESLint와 Prettier 설정 추가

- src/App.jsx
- src/assets/styles/variables.scss
- src/base.scss
- src/components/layout/Header/Header.jsx
- src/components/layout/Header/Header.module.scss
- src/main.jsx
- src/pages/List-page/Test.jsx
* 프리티어, esLingt 적용
* @use 으로 변경
* 멘토님께서 말씀해주신 부분 반영하여 수정(const showButton은 컴포넌트 바깥으로)
> 🐛 fix: 프리티어, eslint적용, 외 코드 일부 수정

- src/api/postUploadImage.js
이미지 업로드 API 변경 및 폼 데이터 수정
이미지 업로드 API 변경 및 폼 데이터 수정
> ♻️ refactor: 이미지 업로드 API 변경 및 폼 데이터 수정

- src/components/UserProfileSelector/UserProfileSelector.jsx
- src/components/recipient/HeaderService/HeaderService.jsx
- src/components/recipient/HeaderService/HeaderService.module.scss
- src/components/recipient/HeaderService/Share/ShareButton.module.scss
- src/utils/share.js
- HeaderService UI : 화면 크기에 따른 레이아웃 변경
- 카카오톡 공유 템플릿 디자인 변경
- 이모지 드롭다운 반응형 디자인 개선
- 이미지 파일 타입 필터링 속성 수정
#87 , #88 , #89 
- 카카오 공유 템플릿 이미지 URL 환경변수를 Vercel에도 추가 설정
> 🎨 style: HeaderService 레이아웃 및 반응형 디자인 개선

- src/components/Card/Card.module.scss
- src/components/Modal/Modal.module.scss
- src/pages/CreateRecipient/CreateRecipient.module.scss
- src/pages/Recipient/Recipient.module.scss
반응형 기준 수정
반응형 기준 수정 (1024px -> 1023px , 768px -> 767px)
> 🎨 style: 반응형 기준 수정 (1024px -> 1023px , 768px -> 767px)

- src/components/Editor/Editor.jsx
♻️ refactor: 에디터 글 정렬 기능 삭제
♻️ refactor: 에디터 글 정렬 기능 삭제
> ♻️ refactor: 에디터 글 정렬 기능 삭제

- src/components/UserProfileSelector/UserProfileSelector.module.scss
- src/components/common/Button.module.scss
- src/pages/RecipientList/RecipientList.module.scss
♻️ refactor: 버튼 여백 조정 및 프로필 이미지 높이 추가
♻️ refactor: 버튼 여백 조정 및 프로필 이미지 높이 추가
> ♻️ refactor: 버튼 여백 조정 및 프로필 이미지 높이 추가

- src/components/RecipientCard/RecipientCard.module.scss
- src/pages/RecipientList/RecipientList.module.scss
> 🎨 style: 모바일에서 ::after 나타나는 에러 수정 시도

- index.html
- src/assets/styles/base.scss
style: 스타일시트 링크 수정 및 글꼴 패밀리 업데이트
style: 스타일시트 링크 수정 및 글꼴 패밀리 업데이트
> 🎨style: 스타일시트 링크 수정 및 글꼴 패밀리 업데이트

- src/assets/styles/base.scss
- src/components/Editor/Editor.jsx
🎨 style: 기본 글꼴 설정을 'Noto Sans'로 추가 및 수정
🎨 style: 기본 글꼴 설정을 'Noto Sans'로 추가 및 수정
> 🎨 style: 기본 글꼴 설정을 'Noto Sans'로 추가 및 수정

- index.html
- src/assets/styles/base.scss
🎨 style: 스타일시트 링크 수정 및 나눔 글꼴 추가
🎨 style: 스타일시트 링크 수정 및 나눔 글꼴 추가
> 🎨 style: 스타일시트 링크 수정 및 나눔 글꼴 추가

- src/components/Editor/Editor.jsx
- src/components/Editor/Editor.module.scss
🎨 style: 폰트 클래스 추가 및 기존 폰트 매핑 제거
🎨 style: 폰트 클래스 추가 및 기존 폰트 매핑 제거
> 🎨 style: 폰트 클래스 추가 및 기존 폰트 매핑 제거

- src/components/recipient/HeaderService/HeaderService.module.scss
- src/components/recipient/HeaderService/Share/ShareButton.module.scss
- 헤더서비스 UI 개선
- 모바일 화면에서의 UI 최적화 : 버튼간 간격 및 버튼 크기
> 🎨 style: 헤더서비스 모바일 UI 개선

- src/components/Card/Card.jsx
- src/components/Modal/Modal.jsx
- src/components/Modal/Modal.module.scss
- src/pages/Recipient/Recipient.module.scss
🎨 style: Modal 컴포넌트에 폰트 클래스 추가 및 적용
🎨 style: Modal 컴포넌트에 폰트 클래스 추가 및 적용
> 🎨 style: Modal 컴포넌트에 폰트 클래스 추가 및 적용

- index.html
- src/pages/Recipient/Recipient.module.scss
뒤로가기 색상 변경
뒤로가기 색상 흰색 검은색 번갈아가게 수정
> 🎨 style: 뒤로가기 버튼 색상 조정

- index.html
🎨 style: 나눔명조 및 나눔손편지 글꼴 추가
🎨 style: 나눔명조 및 나눔손편지 글꼴 추가
> 🎨 style: 나눔명조 및 나눔손편지 글꼴 추가

- src/components/Carousel/Carousel.module.scss
- src/components/CarouselSkeleton/CarouselSkeleton.module.scss
- src/pages/RecipientList/RecipientList.module.scss
* 스켈레톤 반응형 위치 수정
* 반응형 CSS 일부 수정
> 🎨 style: 스켈레톤 반응형 위치 수정

- src/components/FontSelect/FontSelect.jsx
- src/components/recipient/HeaderService/HeaderService.jsx
- src/components/recipient/HeaderService/HeaderService.module.scss
- 이모지 리액션에 옵티미스틱 UI 패턴 적용
- 중복 클릭 방지 및 버튼 비활성화
- 이모지 드래그 방지
#111 , #112
> ✨ feat: 이모지 리액션 옵티미스틱 UI 적용 및 드래그 방지

- src/components/FontSelect/FontSelect.jsx
- src/pages/CreateRecipient/CreateRecipient.jsx
- src/pages/MessageForm/MessageForm.jsx
🐛 fix: 메시지 전송 중복 방지를 위한 상태 관리 추가
🐛 fix: 메시지 전송 중복 방지를 위한 상태 관리 추가
> 🐛 fix: 메시지 전송 중복 방지를 위한 상태 관리 추가

- src/components/common/Button.module.scss
- src/pages/Recipient/Recipient.jsx
으헝너무힘들어요ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ
- allMessages 상태 추가하여 전체 메시지 관리 ( messages 상태에서는 slice로 사용)
- scrollbar 이벤트 추가하여, 스크롤이 움직였을 때 무한스크롤 동작하도록 함
> ✨ feat: Recipient 컴포넌트 메시지 개수 관리

- src/pages/Recipient/Recipient.jsx
> 🐛 fix: 초기 데이터를 6개로만 고정하는 문제 수정

- src/components/Carousel/Carousel.jsx
- src/components/Carousel/Carousel.module.scss
> 🎨 style: 1200이하부터 캐러셀 슬라이드

- src/components/Card/Card.module.scss
> 🎨 style: tablet, mobile에서는 삭제버튼 hover효과 제거

- src/components/Card/Card.module.scss
> 🐛 fix: 마우스가 있는 경우에만! hover 적용

- src/components/Card/Card.module.scss
> 🐛 fix: 모바일에서 버튼이 active상태일때만 스타일 적용

- src/components/Card/Card.module.scss
> 🐛 fix: tablet, mobile용 버튼 호버 삭제

- src/components/Modal/Modal.jsx
- src/hooks/useModalClose.jsx
- src/pages/Recipient/Recipient.jsx
offset 문제 수정
모달 바깥 클릭시 닫히는 기능 추가
offset 문제 수정
모달 바깥 클릭시 닫히는 기능 추가
> offset 문제 수정 및 모달 바깥 클릭시 닫히는 기능 추가

- src/components/RecipientCard/RecipientCard.jsx
>  🐛 fix: 파란 삼각형

- src/pages/Recipient/Recipient.jsx
> 🐛 fix: 페이지 로드중일때 메시지 삭제

- src/components/RecentMessages/RecentMessages.jsx
00명이 작성했어요!의 숫자 부분은, 1억명 이상 작성될 일은 없다고 생각해서 냅둠(..)
> 🐛 fix: recentMessages에 +99로 오버플로우 방지

- src/App.jsx
- src/components/recipient/HeaderService/HeaderService.jsx
- src/utils/numberFormat.js
- 이모지 카운트 포맷팅 기능 추가
- 프로필 +N 카운트 제한 추가
- 라우트(페이지) 단위 코드 스플리팅 적용
1,000이상 - K 단위로 변환(ex. 1.2K)
1,000,000 이상 - M 단위로 변환 (ex. 1.0M)
- 코드 스플리팅을 이용해 초기 번들 크기 감소
> ✨ feat: 이모지 카운트 포맷팅 및 프로필 +N 카운트 제한 기능 추가 / 코드 스플리팅 적용

- src/App.jsx
✨ feat: Suspense 로딩 중 UploadProgressBar 컴포넌트 사용
페이지 이동 시 정적으로 로딩바를 주어서 이동 되는 느낌을 줌
> ✨ feat: Suspense 로딩 중 UploadProgressBar 컴포넌트 사용
